CREATE SCHEMA snet;

CREATE TABLE snet.users (
  userId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  passHash VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  birthday DATE NOT NULL,
  gender VARCHAR(255) NOT NULL,
  imageId BIGINT NULL
);

CREATE TABLE snet.messages (
  messageId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  senderId BIGINT NOT NULL,
  receiverId BIGINT NOT NULL,
  sendingTime DATETIME NOT NULL,
  messageBody VARCHAR(255),
  unread BOOL DEFAULT TRUE
);

CREATE TABLE snet.images(
  imageId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  image BLOB
);
